# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calc_mu_log <- function(x, beta, offset) {
    .Call(`_sprintr_glm_calc_mu_log`, x, beta, offset)
}

logistic <- function(x, y, offset) {
    .Call(`_sprintr_glm_logistic`, x, y, offset)
}

calc_mu_pois <- function(x, beta, offset) {
    .Call(`_sprintr_glm_calc_mu_pois`, x, beta, offset)
}

poisson <- function(x, y, offset) {
    .Call(`_sprintr_glm_poisson`, x, y, offset)
}

calc_mu_multi <- function(x, beta, offset) {
    .Call(`_sprintr_glm_calc_mu_multi`, x, beta, offset)
}

multi <- function(x, y, offset, K) {
    .Call(`_sprintr_glm_multi`, x, y, offset, K)
}

calc_delta_ordinal <- function(etaMat) {
    .Call(`_sprintr_glm_calc_delta_ordinal`, etaMat)
}

calc_eta_ordinal <- function(delta) {
    .Call(`_sprintr_glm_calc_eta_ordinal`, delta)
}

tran_xspan <- function(x, K) {
    .Call(`_sprintr_glm_tran_xspan`, x, K)
}

tran_yspan <- function(y, n, K) {
    .Call(`_sprintr_glm_tran_yspan`, y, n, K)
}

ordinal <- function(x, y, offset, n, K) {
    .Call(`_sprintr_glm_ordinal`, x, y, offset, n, K)
}

ordinal_sparse <- function(x, y, yMat, offset, n, K) {
    .Call(`_sprintr_glm_ordinal_sparse`, x, y, yMat, offset, n, K)
}

#' Sure Independence Screening in Step 2
#'
#' @param x a n-by-p matrix of main effects, with i.i.d rows, and each row represents a vector of observations of p main-effects
#' @param y a response vector of size \code{n}. \code{y} is a vector of continuous data in "gaussian" family; a vector of positive count data in "poisson" family; a vector of 0-1 binary data in "binomial" family. Notice that \code{y} should be a factor when using the "ordinal" family for ordinal response.
#' @param nlev the number of levels for response variable. Set to 1 for "gaussian" and "poisson" family.
#' @param offset the linear predictions from Step 1.
#' @param num_keep the number of candidate interactions in Step 2. Default to be n.
#' @param square An indicator of whether squared effects should be considered in Step 1 (NOT Step 2!). square == TRUE if squared effects have been considered in Step 1, i.e., squared effects will NOT be considered in Step 2.
#' @param main_effect An indicator of whether main effects should also be screened. Default to be false.
#' @param family Either a character string representing one of the built-in exponential families, including "gaussian", "poisson", "binomial", "ordinal". Default is "gaussian".
#' @return a three-column matrix representing the index pair of the selected interactions and its MML with the response vector given by the \code{offset}.
#' @export
screen_cpp <- function(x, y, nlev, offset, num_keep, square = FALSE, main_effect = FALSE, family = "gaussian") {
    .Call(`_sprintr_glm_screen_cpp`, x, y, nlev, offset, num_keep, square, main_effect, family)
}

#' Sure Independence Screening in Step 2 for sparse design matrix
#'
#' @param x a n-by-p sparse matrix of main effects.
#' @param y a response vector of size \code{n}. \code{y} is a vector of continuous data in "gaussian" family; a vector of positive count data in "poisson" family; a vector of 0-1 binary data in "binomial" family. Notice that \code{y} should be a factor when using the "ordinal" family for ordinal response.
#' @param yMat Default to be empty in "gaussian", "binomial" and "poisson" family. In "ordinal" family, it transforms an ordinal response vector \code{y} to a sparse \code{n}-by-\code{nlev} matrix with element 1 denoting the i-th observation with the j-th ordered level.
#' @param nlev the number of levels for response variable. Set to 1 for "gaussian" and "poisson" family.
#' @param offset the linear predictions from Step 1.
#' @param num_keep the number of candidate interactions in Step 2. Default to be n.
#' @param square An indicator of whether squared effects should be considered in Step 1 (NOT Step 2!). square == TRUE if squared effects have been considered in Step 1, i.e., squared effects will NOT be considered in Step 2.
#' @param main_effect An indicator of whether main effects should also be screened. Default to be false.
#' @param family Either a character string representing one of the built-in exponential families, including "gaussian", "poisson", "binomial", "ordinal". Default is "gaussian".
#' @return a three-column matrix representing the index pair of the selected interactions and its MML with the response vector given by the \code{offset}.
#' @export
screen_sparse_cpp <- function(x, y, yMat, nlev, offset, num_keep, square = FALSE, main_effect = FALSE, family = "gaussian") {
    .Call(`_sprintr_glm_screen_sparse_cpp`, x, y, yMat, nlev, offset, num_keep, square, main_effect, family)
}

